project:
  type: website
  output-dir: docs
  #resources: 
  #  - "*.css"
    
execute:
  freeze: auto

website:
  title: "ArewaDS FellowShip"
  site-url: "https://arewadatascience.github.io"
  repo-url: https://github.com/arewadataScience/arewadatascience
  repo-actions: issue
  #image: images/logo.png
  navbar:
    #logo: ELLAKAYE-logo-light.png
    title: "AREWA Data Science<span class='icon-line'></span>2022 FELLOWSHIP"
    right:
      - text: about
        href: about.qmd
      - text: posts
        href: posts.qmd
      - text: Fellows
        href: fellows.qmd
      - text: Mentors
        href: mentors.qmd
      - text: Projects
        href: projects.qmd
      - text: contact
        href: contact.qmd
      #- icon: github
      #  href: https://github.com/EllaKaye
      #- icon: twitter
      #  href: https://twitter.com/ellamkaye
  #favicon: images/logo.png
  twitter-card: 
  #  title: Arewa DS
   # description: The website of Arewa Data Science
  #  image: images/logo.png
    #image-alt: |
     # A square logo made from Ella Kaye's name - 
      #first name on top of last name in dark gray capital letters, 
      #separated by a horizontal bright pink line, on a very light grey background
    image-width: 500
    image-height: 500
    card-style: summary # alternative summary_large_image
    creator: "@shmuhammadd"
    site: "@shmuhammadd"
  open-graph: 
    #description: The personal website of Ella Kaye
    image: images/logo.png
    image-width: 500
    image-height: 500
    locale: en-GB
  google-analytics:
    tracking-id: "G-7G8FLLRS4M"
    anonymize-ip: true
  #   
  # page-footer: 
  #   left: "Copyright 2021, Norah Jones" 
  #   right: 
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter 
  #       href: https://twitter.com/ 
        
  page-footer:
    border: true
    #left: "Published with [Quarto](https://quarto.org/) | Hosted by Github pages served by Github Action [{{< iconify simple-icons netlify >}}](https://www.netlify.com)"
    right: "© 2022 [Arewa DataScience FellowShip](/about.html) [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  
format:
  html:
    theme: 
    
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source

